
// const AUTH_BEGIN = 'AUTH_BEGIN';
// const AUTH_ERR = 'AUTH_ERR';
// const AUTH_SUCCESS = 'AUTH_SUCCESS';


const actiontyps = {
    INSTRUCTOR_COURSE_LISTING_BEGIN:'INSTRUCTOR_COURSE_LISTING_BEGIN',
    INSTRUCTOR_COURSE_LISTING_ERR:'INSTRUCTOR_COURSE_LISTING_ERR',
    INSTRUCTOR_COURSE_LISTING_SUCCESS:'INSTRUCTOR_COURSE_LISTING_SUCCESS'
}

export default actiontyps;