
// const AUTH_BEGIN = 'AUTH_BEGIN';
// const AUTH_ERR = 'AUTH_ERR';
// const AUTH_SUCCESS = 'AUTH_SUCCESS';


const actiontyps = {
    COURSES_BEGIN:'COURSES_BEGIN',
    COURSES_ERR:'COURSES_ERR',
    COURSES_SUCCESS:'COURSES_SUCCESS',

    COURSE_BEGIN:'COURSE_BEGIN',
    COURSE_ERR:'COURSE_ERR',
    COURSE_SUCCESS:'COURSE_SUCCESS',

    COURSE_CREATE_BEGIN:'COURSE_CREATE_BEGIN',
    COURSE_CREATE_ERR:'COURSE_CREATE_ERR',
    COURSE_CREATE_SUCCESS:'COURSE_CREATE_SUCCESS',

    BATCH_CREATE_BEGIN:'BATCH_CREATE_BEGIN',
    BATCH_CREATE_ERR:'BATCH_CREATE_ERR',
    BATCH_CREATE_SUCCESS:'BATCH_CREATE_SUCCESS',

    BATCH_BEGIN:'BATCH_BEGIN',
    BATCH_ERR:'BATCH_ERR',
    BATCH_SUCCESS:'BATCH_SUCCESS',
}

export default actiontyps;